### PR TITLE
added ability to set the priority

### PR DESCRIPTION
**Pull request by raffaelespazzoli**
Signed-off-by: raffaelespazzoli <raffaele.spazzoli@gmail.com>

added ability to set the priority on the low priority pods

### CODE REVIEW

**Review by sabre1041 — CHANGES_REQUESTED** [review]
Looks like you are missing changes to the generated `redhatcop.redhat.io_nodescalingwatermarks.yaml` CRD file

**Comment by raffaelespazzoli** [comment]
> Looks like you are missing changes to the generated `redhatcop.redhat.io_nodescalingwatermarks.yaml` CRD file

I don't understand what you mean. plus what does it matter if it is a generated file?

**Comment by raffaelespazzoli** [comment]
I understood what you mean, issue should be addressed now. @sabre1041

**Review by sabre1041 — APPROVED** [review]
LGTM

**Pull request merged**
